# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"acc_cm": "model.ipynb",
         "RNN": "model.ipynb",
         "device": "namegen.ipynb",
         "PAD_ID": "model.ipynb",
         "get_dataset": "namegen.ipynb",
         "after_item": "namegen.ipynb",
         "pad_input_chunk_new": "namegen.ipynb",
         "train_from_scratch": "namegen.ipynb",
         "nn.Module.gen_name": "namegen.ipynb",
         "load_from_checkpoint": "namegen.ipynb",
         "get_first_name_model": "namegen.ipynb"}

modules = ["seq2seq/model.py",
           "seq2seq/namegen.py"]

doc_url = "https://puneet.github.io/mllib/"

git_url = "https://github.com/puneet/mllib/tree/main/"

def custom_doc_links(name): return None
