# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://puneet.github.io/mllib/"

git_url = "https://github.com/puneet/mllib/tree/main/"

def custom_doc_links(name): return None
